require('dotenv').config();
const Alpaca = require('@alpacahq/alpaca-trade-api');
const fs = require('fs');
const path = require('path');

interface NormalizedBar {
  timestamp: string;
    open: number;
      high: number;
        low: number;
          close: number;
            volume: number;
            }

            async function getAAPLData() {
              // Check credentials
                if (!process.env.ALPACA_KEY_ID || !process.env.ALPACA_SECRET_KEY) {
                    console.error('Error: Missing ALPACA_KEY_ID or ALPACA_SECRET_KEY in .env file');
                        process.exit(1);
                          }

                            const alpaca = new Alpaca({
                                keyId: process.env.ALPACA_KEY_ID,
                                    secretKey: process.env.ALPACA_SECRET_KEY,
                                        paper: true,
                                          });

                                            try {
                                                const endDate = new Date();
                                                    const startDate = new Date();
                                                        startDate.setDate(endDate.getDate() - 30);

                                                            let normalizedBars: NormalizedBar[] = [];

                                                                try {
                                                                      // Try getBarsV2 first (iterative version)
                                                                            const barsV2 = await alpaca.getBarsV2('AAPL', {
                                                                                    start: startDate.toISOString(),
                                                                                            end: endDate.toISOString(),
                                                                                                    timeframe: '1Day',
                                                                                                            limit: 30
                                                                                                                  });

                                                                                                                        for await (let bar of barsV2) {
                                                                                                                                normalizedBars.push({
                                                                                                                                          timestamp: new Date(bar.t).toISOString(),
                                                                                                                                                    open: bar.o,
                                                                                                                                                              high: bar.h,
                                                                                                                                                                        low: bar.l,
                                                                                                                                                                                  close: bar.c,
                                                                                                                                                                                            volume: bar.v
                                                                                                                                                                                                    });
                                                                                                                                                                                                          }
                                                                                                                                                                                                              } catch (v2Error) {
                                                                                                                                                                                                                    // Fallback to getBars (classic version)
                                                                                                                                                                                                                          const barsClassic = await alpaca.getBars('1Day', 'AAPL', {
                                                                                                                                                                                                                                  start: startDate.toISOString(),
                                                                                                                                                                                                                                          end: endDate.toISOString(),
                                                                                                                                                                                                                                                  limit: 30
                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                              if (barsClassic.AAPL) {
                                                                                                                                                                                                                                                                      normalizedBars = barsClassic.AAPL.map((bar: any) => ({
                                                                                                                                                                                                                                                                                timestamp: new Date(bar.time).toISOString(),
                                                                                                                                                                                                                                                                                          open: bar.open,
                                                                                                                                                                                                                                                                                                    high: bar.high,
                                                                                                                                                                                                                                                                                                              low: bar.low,
                                                                                                                                                                                                                                                                                                                        close: bar.close,
                                                                                                                                                                                                                                                                                                                                  volume: bar.volume
                                                                                                                                                                                                                                                                                                                                          }));
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        // Create data directory
                                                                                                                                                                                                                                                                                                                                                            const dataDir = path.join(process.cwd(), 'data');
                                                                                                                                                                                                                                                                                                                                                                if (!fs.existsSync(dataDir)) {
                                                                                                                                                                                                                                                                                                                                                                      fs.mkdirSync(dataDir, { recursive: true });
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                              // Create CSV content
                                                                                                                                                                                                                                                                                                                                                                                  const csvHeader = 'timestamp,open,high,low,close,volume\n';
                                                                                                                                                                                                                                                                                                                                                                                      const csvRows = normalizedBars.map(bar => 
                                                                                                                                                                                                                                                                                                                                                                                            `${bar.timestamp},${bar.open},${bar.high},${bar.low},${bar.close},${bar.volume}`
                                                                                                                                                                                                                                                                                                                                                                                                ).join('\n');
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        const csvContent = csvHeader + csvRows;
                                                                                                                                                                                                                                                                                                                                                                                                            const csvPath = path.join(dataDir, 'aapl_data.csv');
                                                                                                                                                                                                                                                                                                                                                                                                                fs.writeFileSync(csvPath, csvContent);

                                                                                                                                                                                                                                                                                                                                                                                                                    // Print results
                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Total bars received: ${normalizedBars.length}`);
                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('\nFirst 5 bars:');
                                                                                                                                                                                                                                                                                                                                                                                                                                normalizedBars.slice(0, 5).forEach((bar, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`${index + 1}:`, bar);
                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log(`\nCSV saved to: ${path.resolve(csvPath)}`);

                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Error fetching AAPL data:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (err.response) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error('Status:', err.response.status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Data:', err.response.data);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.error(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        getAAPLData();